import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "@/redux/StoreProvider";
import { Toaster } from "react-hot-toast";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-[100vw] h-[auto] bg-[#0c0032] flex justify-center items-center overflow-x-hidden`}
      >
        {children}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
      </StoreProvider>
    </html>
  );
}
